<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>cloud.muer</groupId><artifactId>muer-parent</artifactId><version>0.1.0</version>
        <relativePath>../../pom.xml</relativePath></parent><artifactId>muer-diagnostics</artifactId><name>Muer Diagnostics</name><dependencies><dependency><groupId>cloud.muer</groupId><artifactId>muer-authorization</artifactId><version>${project.version}</version></dependency><dependency><groupId>org.junit.jupiter</groupId><artifactId>junit-jupiter</artifactId><scope>test</scope></dependency></dependencies></project>
