<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.wust.iam</groupId>
        <artifactId>iam-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>
    <artifactId>iam-spring-boot-autoconfigure</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.wust.iam</groupId>
            <artifactId>iam-authentication</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.wust.iam</groupId>
            <artifactId>iam-authorization</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.wust.iam</groupId>
            <artifactId>iam-diagnostics</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.wust.iam</groupId>
            <artifactId>iam-management-web</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.wust.iam</groupId>
            <artifactId>iam-persistence-mybatis</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-config</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
