<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>com.wust.iam</groupId><artifactId>iam-parent</artifactId><version>0.1.0-SNAPSHOT</version></parent><artifactId>iam-authorization</artifactId><dependencies><dependency><groupId>com.wust.iam</groupId><artifactId>iam-core</artifactId><version>${project.version}</version></dependency><dependency><groupId>org.junit.jupiter</groupId><artifactId>junit-jupiter</artifactId><scope>test</scope></dependency></dependencies></project>
